### ISSUE TITLE
CorpseFlyPathfinder crashes when dying

### ISSUE THREAD

**Issue by melvinczyk** [melvinczyk/Born_in_spellbooks#5]
Suspected line: 
at net.melvinczyk.borninspellbooks.entity.mobs.CorpseFlyPathFinder.popAndDie(CorpseFlyPathFinder.java:254) ~[%23189!/:?] {re:classloading}
	at net.melvinczyk.borninspellbooks.entity.mobs.CorpseFlyPathFinder.tick(CorpseFlyPathFinder.java:103) ~[%23189!/:?] {re:classloading}

**Comment by melvinczyk** [comment]
fixed in a1f2210323d65624a24f3ca19c85f74bca781534
